import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#663700",
        "primary-container": "#854d0e",
        "primary-fixed": "#ffdcc0",
        "primary-fixed-dim": "#ffb877",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffc898",
        "on-primary-fixed": "#2d1600",
        "on-primary-fixed-variant": "#6b3b00",
        "inverse-primary": "#ffb877",

        surface: "#fff8f5",
        "surface-bright": "#fff8f5",
        "surface-dim": "#e0d8d5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#faf2ee",
        "surface-container": "#f4ece8",
        "surface-container-high": "#eee7e3",
        "surface-container-highest": "#e9e1dd",
        "surface-variant": "#e9e1dd",
        "surface-tint": "#8a5112",
        "on-surface": "#1e1b19",
        "on-surface-variant": "#524439",
        "inverse-surface": "#33302d",
        "inverse-on-surface": "#f7efeb",

        secondary: "#006d30",
        "secondary-container": "#92f5a4",
        "secondary-fixed": "#95f8a7",
        "secondary-fixed-dim": "#79db8d",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007233",
        "on-secondary-fixed": "#00210a",
        "on-secondary-fixed-variant": "#005323",

        tertiary: "#004865",
        "tertiary-container": "#006186",
        "tertiary-fixed": "#c5e7ff",
        "tertiary-fixed-dim": "#8acff9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#9fdaff",
        "on-tertiary-fixed": "#001e2d",
        "on-tertiary-fixed-variant": "#004c6a",

        outline: "#857467",
        "outline-variant": "#d7c3b4",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        background: "#fff8f5",
        "on-background": "#1e1b19",
      },
      fontFamily: {
        arabic: ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "title-md": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "body-sm": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "display-lg": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "label-sm": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "headline-md": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "label-md": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "headline-lg": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "currency-md": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "display-lg-mobile": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "body-md": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
        "body-lg": ['"IBM Plex Sans Arabic"', "IBM Plex Sans", "sans-serif"],
      },
      spacing: {
        gutter: "1rem",
        "margin-mobile": "1rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "0.75rem",
        "space-xl": "2rem",
        "space-sm": "0.5rem",
        margin: "2rem",
      },
      fontSize: {
        "title-md": ["17px", { lineHeight: "24px", letterSpacing: "0px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0px", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "52px", letterSpacing: "0px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.2px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "0px", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0px", fontWeight: "500" }],
        "headline-lg-mobile": ["22px", { lineHeight: "30px", letterSpacing: "0px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "38px", letterSpacing: "0px", fontWeight: "600" }],
        "currency-md": ["16px", { lineHeight: "24px", letterSpacing: "0px", fontWeight: "600" }],
        "display-lg-mobile": ["30px", { lineHeight: "40px", letterSpacing: "0px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
